# Generated by Django 4.2.2 on 2023-06-21 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='category',
        ),
    ]
